name: Déploiement

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation de pnpm
        run: npm install -g pnpm

      - name: Navigate to project directory
        run: cd website
        
      - name: Installation des dépendences
        run: pnpm install
