name: Déploiement

on:
  push:
    branches:
      - "feature/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Installation de pnpm
        run: npm install -g pnpm
        
      - name: Installation des dépendences
        run: pnpm install

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the 'test' job runs after the 'build' job completes
    outputs:
      test-status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Installation de pnpm
        run: npm install -g pnpm  # You may skip this if pnpm is already installed in 'build'

      - name: Installation des dépendences
        run: pnpm install  # You may skip this if dependencies are already installed in 'build'

      - name: Tests unitaires
        run: |
          if ! pnpm test; then
            echo "::set-output name=test-status::failure"
            exit 1
          fi

  cancel-push:
    runs-on: ubuntu-latest
    needs: test  # Wait for 'test' job to complete
    if: ${{ needs.test.outputs.test-status == 'failure' }}  # Cancel only if 'test' job fails
    steps:
      - name: Cancel Push
        run: echo "Tests failed, cancelling push."
