name: Déploiement

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Installation de pnpm
        run: npm install -g pnpm
        
      - name: Installation des dépendences
        run: pnpm install

      - name: Build
        run: pnpm run build
